version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install --upgrade awscli
  pre_build:
    commands:
      - python -m unittest discover test
  build:
    commands:
      - sam build
      - export BUCKET=lambda-package-deploy-01
      - sam package --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
